_convert_: all
_target_: navsim.common.dataclasses.SceneFilter
frame_interval: 1
has_route: true
log_names:
- 2021.06.09.17.37.09_veh-12_04489_04816-d73caeda671c5bf6-000
- 2021.07.09.02.42.50_veh-35_00038_02629-03f6cbb970625cdc-000
- 2021.07.09.02.42.50_veh-35_00038_02629-5ab2282dc4a356c6-000
- 2021.07.09.17.06.37_veh-35_02609_05015-7b9e548ccad85bda-000
- 2021.07.09.17.06.37_veh-35_02609_05015-c31674941f9b51b5-000
- 2021.10.05.07.49.39_veh-52_00934_01406-6db4868738c25921-000
- 2021.10.05.07.49.39_veh-52_00934_01406-aecfe3d39819549c-000
- 2021.10.11.08.31.07_veh-50_02360_02684-2fb17d18ba345719-000
max_scenes: null
num_future_frames: 8
num_history_frames: 4
tokens:
- d73caeda671c5bf6-000
- 03f6cbb970625cdc-000
- 5ab2282dc4a356c6-000
- 7b9e548ccad85bda-000
- c31674941f9b51b5-000
- 6db4868738c25921-000
- aecfe3d39819549c-000
- 2fb17d18ba345719-000
