_target_: navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: navsim.agents.diffusiondrive.transfuser_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  bkb_path: ${oc.env:OPENSCENE_DATA_ROOT}/models/resnet34_model.bin
  plan_anchor_path: ${oc.env:NAVSIM_DEVKIT_ROOT}/traj_final/kmeans_navsim_traj_20.npy

  latent: True

checkpoint_path: null
lr: 6e-4
